ARG PYTHON_VERSION=3.10.2-slim-bullseye

FROM python:$(PYTHON_VERSION) as python

FROM python as python-build-stage
ARG BUILD_ENVIRONMENT=development


RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential \
    libqd-dev

COPY ./requirements .

RUN pip wheel --wheel-dir /usr/src/app/wheels \
    -r ${BUILD_ENVIRONMENT}}.txt

FROM python as python-run-stage 
ARG BUILD_ENVIRONMENT=development
ARG APP_HOME=/app

# Environment Variables

# Prevents .pyc files
ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONBUFFERED 1

ENV BUILD_ENV $(BUILD_ENVIRONMENT)

WORKDIR $(APP_HOME)

RUN apt-get update && apt-get install --no-install-recommends -y \
    libqd-dev \
    gettext \
    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
    && rm -rf /var/lib/apt/lists/*

COPY --from=python-build-stage /usr/src/app/wheels /wheels/

RUN pip install --no-cache-dir --no-index --find-links=/wheels/ /wheels/* \
    && rm -rf /wheels/

COPY ./docker/local/django/entrypoint /entrypoint
RUN sed -i 's/\r$//g' /entrypoint
RUN chmod +x /entrypoint

COPY ./docker/local/django/start /start
RUN sed -i 's/\r$//g' /start
RUN chmod +x /start

COPY . $(APP_HOME)

ENTRYPOINT ["/entrypoint"]



