version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/development/django/Dockerfile
    command: /start
    container_name: django-api
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - "8000"
    env_file:
      - ./.envs/.development/.django
      - ./.envs/.development/.postgres
    depends_on:
      - postgres
      - mailhog
      - redis
    networks:
      - django-api-live


  postgres:
    build:
      context: .
      dockerfile: ./docker/development/postgres/Dockerfile
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.development/.postgres
    networks:
      - django-api-live
  
  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports: 
      - "8025:8025"
    networks:
      - django-api-live

  redis:
    image: redis:6-alpine
    container_name: redis
    networks:
      - django-api-live
  
  celery_worker:
    build:
      context: .
      dockerfile: ./docker/development/django/Dockerfile
    command: /start-celery-worker
    container_name: celery_worker
    volumes:
      - .:/app
    env_file:
      - ./.envs/.development/.django
      - ./.envs/.development/.postgres
    depends_on:
      - redis
      - postgres
      - mailhog
    networks:
      - django-api-live
  
  flower:
    build:
      context: .
      dockerfile: ./docker/development/django/Dockerfile
    command: /start-flower
    container_name: flower
    volumes:
      - .:/app
    env_file:
      - ./.envs/.development/.django
      - ./.envs/.development/.postgres
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - postgres
    networks:
      - django-api-live


  nginx:
    restart: always
    depends_on:
      - api
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    build:
      context: ./docker/development/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - django-api-live

networks:
  django-api-live:
    driver: bridge

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  static_volume: 
  media_volume: 