#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A django_api inspect ping
}

until worker_ready; do
    >&2 echo "Celery workers are not available"
done
>&2 echo "Celery workers are ready and available"

celery -A django_api \
    --broker="${CELERY_BROKER}" \
    flower \
    --basic-auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
